[profile.default]
  evm_version="paris"
  ffi=true
  remappings=[
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "leb128=lib/leb128-nooffset/src/",
    "permit2/=lib/permit2/",
    "solady/=lib/solady/src/",
    "@sphinx-labs/plugins/=node_modules/@sphinx-labs/plugins/contracts/foundry/",
    "@sphinx-labs/contracts/=node_modules/@sphinx-labs/contracts/",
    "sphinx-forge-std/=node_modules/sphinx-forge-std/src/",
    "sphinx-solmate/=node_modules/sphinx-solmate/src/"
  ]
  solc_version="0.8.23"

[profile.ci]
  fuzz_runs=5000
  libs     =["lib"]
  optimizer=false
  out      ="out"

[profile.deploy]
  fs_permissions=[{access="read", path="./out"}, {access="read-write", path="./cache"}]
  extra_output  =['storageLayout']
  build_info    =true
  optimizer     =true
  optimizer_runs=10_000_000
  via_ir        =true

[rpc_endpoints]
  arbitrum        ="https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  arbitrum_sepolia="https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  avalanche       ="https://avalanche-mainnet.infura.io/v3/${INFURA_API_KEY}"
  avalanche_fuji  ="https://avalanche-fuji.infura.io/v3/${INFURA_API_KEY}"
  base            ="https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  base_sepolia    ="https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  ethereum        ="https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  linea           ="https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"
  linea_goerli    ="https://linea-goerli.infura.io/v3/${INFURA_API_KEY}"
  optimism        ="https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  optimism_sepolia="https://opt-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  polygon         ="https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  polygon_mumbai  ="https://polygon-mumbai.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  sepolia         ="https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"